# Generated by Django 5.2.6 on 2025-09-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price'),
    ]

    operations = [
    ]
